/** Fictional, clearly labelled development fixtures. Photos use the existing Pexels collection. */
const photo = (id: number, width = 900, height = 1200) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=${width}&h=${height}`;

export const demoProducts = [
  { name: 'ترنچ‌کت شنی کلاسیک', brand: 'کلبه وینتیج', category: 'کت و پالتو', description: 'ترنچ‌کت دو ردیف دکمه با پارچهٔ کتان متراکم، کمربند قابل تنظیم و آستر سبک؛ مناسب لایه‌پوشی پاییز.', colors: ['شنی', 'کرم'], sizes: ['S', 'M', 'L'], cash: '49800000', wholesale: '36500000', gender: 'women', genderCode: 'female', seasons: ['autumn', 'spring'], vibes: ['old-money', 'classic'], fabric: 'کتان متراکم', images: [photo(12349052), photo(7760027)] },
  { name: 'بلیزر پشمی سرمه‌ای', brand: 'کلبه وینتیج', category: 'کت و پالتو', description: 'بلیزر تک‌دکمه با سرشانهٔ ساختارمند و پارچهٔ پشم سبک؛ برای استایل اداری و نیمه‌رسمی.', colors: ['سرمه‌ای', 'مشکی'], sizes: ['M', 'L', 'XL'], cash: '62500000', wholesale: '47200000', gender: 'men', genderCode: 'male', seasons: ['autumn', 'winter'], vibes: ['old-money', 'classic'], fabric: 'پشم سبک', images: [photo(8483838), photo(19778358)] },
  { name: 'پیراهن آکسفورد سفید', brand: 'کلبه وینتیج', category: 'پیراهن و شومیز', description: 'پیراهن آکسفورد صددرصد پنبه با یقهٔ دکمه‌دار و برش آزادِ مرتب؛ مناسب استفادهٔ روزمره.', colors: ['سفید', 'آبی روشن'], sizes: ['S', 'M', 'L', 'XL'], cash: '18900000', wholesale: '13900000', gender: 'men', genderCode: 'male', seasons: ['spring', 'summer', 'autumn'], vibes: ['minimal', 'classic'], fabric: 'پنبه آکسفورد', images: [photo(8306364), photo(9558723)] },
  { name: 'شومیز لینن یقه‌دار', brand: 'کلبه وینتیج', category: 'پیراهن و شومیز', description: 'شومیز لینن تنفس‌پذیر با یقهٔ کلاسیک و دکمه‌های صدفی؛ برای روزهای گرم و استایل مینیمال.', colors: ['شیری', 'زیتونی'], sizes: ['S', 'M', 'L'], cash: '22400000', wholesale: '16500000', gender: 'women', genderCode: 'female', seasons: ['spring', 'summer'], vibes: ['quiet-luxury', 'minimal'], fabric: 'لینن طبیعی', images: [photo(7671168), photo(9594681)] },
  { name: 'شلوار پارچه‌ای پیلی‌دار', brand: 'کلبه وینتیج', category: 'شلوار', description: 'شلوار راسته با دو پیلی و فاق متوسط؛ پارچهٔ خوش‌افت برای ست‌کردن با پیراهن و بلیزر.', colors: ['کرم', 'ذغالی'], sizes: ['S', 'M', 'L', 'XL'], cash: '29600000', wholesale: '21900000', gender: 'women', genderCode: 'female', seasons: ['autumn', 'winter', 'spring'], vibes: ['old-money', 'workwear'], fabric: 'فاستونی سبک', images: [photo(9968536), photo(7760026)] },
  { name: 'پالتوی بلند زرشکی', brand: 'کلبه وینتیج', category: 'کت و پالتو', description: 'پالتوی بلند با یقهٔ برگردان و کمربند پارچه‌ای؛ برش کلاسیک برای روزهای سرد.', colors: ['زرشکی', 'شتری'], sizes: ['M', 'L', 'XL'], cash: '78900000', wholesale: '59800000', gender: 'women', genderCode: 'female', seasons: ['winter'], vibes: ['dark-academia', 'classic'], fabric: 'پشم و کشمیر', images: [photo(36379088), photo(36379080)] },
  { name: 'کت لینن دو دکمه', brand: 'کلبه وینتیج', category: 'کت و پالتو', description: 'کت سبک لینن با دو دکمه و جیب‌های پاکتی؛ انتخابی راحت برای قرارهای بهاری.', colors: ['شنی', 'زیتونی'], sizes: ['M', 'L', 'XL'], cash: '52800000', wholesale: '39900000', gender: 'men', genderCode: 'male', seasons: ['spring', 'summer'], vibes: ['quiet-luxury', 'classic'], fabric: 'لینن و پنبه', images: [photo(8484005), photo(20447402)] },
  { name: 'پیراهن چهارخانه فلانل', brand: 'کلبه وینتیج', category: 'پیراهن و شومیز', description: 'پیراهن فلانل نرم با چهارخانهٔ ریز و برش استاندارد؛ برای لایه‌پوشی پاییز و زمستان.', colors: ['سرمه‌ای', 'قهوه‌ای'], sizes: ['M', 'L', 'XL'], cash: '21500000', wholesale: '15800000', gender: 'men', genderCode: 'male', seasons: ['autumn', 'winter'], vibes: ['dark-academia', 'workwear'], fabric: 'فلانل پنبه‌ای', images: [photo(20447402), photo(8483478)] },
  { name: 'لوفر چرمی قهوه‌ای', brand: 'کلبه وینتیج', category: 'کفش و بوت', description: 'لوفر چرمی با رویهٔ نرم، زیرهٔ مقاوم و فرم کلاسیک؛ مناسب استایل رسمی و روزمره.', colors: ['قهوه‌ای'], sizes: ['40', '41', '42', '43'], cash: '43700000', wholesale: '32800000', gender: 'men', genderCode: 'male', seasons: ['spring', 'summer', 'autumn'], vibes: ['old-money', 'classic'], fabric: 'چرم طبیعی', images: [photo(18054235), photo(20763458)] },
  { name: 'پلیور بافت کرم', brand: 'کلبه وینتیج', category: 'بافت و هودی', description: 'پلیور بافت نرم با یقهٔ گرد و الیاف گرم؛ انتخابی ساده برای لایه‌پوشی زمستان.', colors: ['کرم'], sizes: ['S', 'M', 'L'], cash: '27900000', wholesale: '20400000', gender: 'women', genderCode: 'female', seasons: ['autumn', 'winter'], vibes: ['minimal', 'quiet-luxury'], fabric: 'پشم و پنبه', images: [photo(5788999)] },
  { name: 'کیف دستی چرم قهوه‌ای', brand: 'کلبه وینتیج', category: 'اکسسوری', description: 'کیف دستی چرمی با بند قابل تنظیم و فضای مناسب برای وسایل ضروری روزمره.', colors: ['قهوه‌ای'], sizes: ['One Size'], cash: '46900000', wholesale: '35200000', gender: 'women', genderCode: 'female', seasons: ['spring', 'summer', 'autumn', 'winter'], vibes: ['classic', 'quiet-luxury'], fabric: 'چرم طبیعی', images: [photo(27100523)] },
] as const;

export const demoArticles = [
  { slug: 'autumn-trench-guide', title: 'چطور یک ترنچ‌کت ماندگار انتخاب کنیم؟', excerpt: 'از جنس پارچه و خط شانه تا قد مناسب؛ نکته‌هایی برای انتخاب بارانی‌ای که چند فصل همراهتان بماند.', body: 'ترنچ‌کت خوب از پارچه‌ای شروع می‌شود که در برابر استفادهٔ روزمره فرم خود را حفظ کند. هنگام پرو، حرکت آزاد شانه و جای کافی برای یک لایه لباس زیر کت را بررسی کنید. قد تا میانهٔ زانو برای اغلب استایل‌ها انعطاف بیشتری دارد. رنگ‌های شنی و سرمه‌ای به‌راحتی با کمد موجود هماهنگ می‌شوند. برای نگهداری، پس از هر بار استفاده کت را روی چوب‌لباسی پهن آویزان کنید و دستور شست‌وشوی پارچه را دنبال کنید.', category: 'راهنمای خرید', tags: ['ترنچ‌کت', 'پاییز', 'راهنمای خرید'], cover: photo(9968536, 1200, 750) },
  { slug: 'capsule-wardrobe', title: 'کمد کپسولی با هشت لباس کاربردی', excerpt: 'چند قطعهٔ خوش‌دوخت می‌توانند ده‌ها ترکیب روزمره و نیمه‌رسمی بسازند.', body: 'برای شروع یک کمد کپسولی، لباس‌هایی را انتخاب کنید که دست‌کم با سه قطعهٔ دیگر ترکیب شوند. یک پیراهن سفید، شلوار پارچه‌ای، بلیزر تیره و بافت خنثی پایهٔ خوبی هستند. سپس رنگ‌های مکمل و بافت‌های متفاوت اضافه کنید. تناسب اندام و کیفیت دوخت از تعداد لباس‌ها مهم‌تر است؛ انتخاب کمتر و دقیق‌تر به استفادهٔ بیشتر از هر لباس کمک می‌کند.', category: 'استایل', tags: ['کمد کپسولی', 'استایل', 'مینیمال'], cover: photo(36593273, 1200, 750) },
  { slug: 'fabric-care', title: 'نگهداری از پشم، لینن و پنبه', excerpt: 'با چند عادت ساده، ظاهر و عمر لباس‌های محبوبتان را حفظ کنید.', body: 'پشم را بین دو بار پوشیدن استراحت دهید و برای تمیز کردن لکه‌ها از برس نرم استفاده کنید. لینن را با شویندهٔ ملایم و دمای پایین بشویید؛ چروک طبیعی آن بخشی از بافت پارچه است. لباس پنبه‌ای را بر اساس رنگ جدا کنید و از خشک‌کردن طولانی زیر آفتاب مستقیم بپرهیزید. همیشه برچسب مراقبت همان لباس را ملاک اصلی قرار دهید.', category: 'مراقبت از لباس', tags: ['پارچه', 'پشم', 'لینن'], cover: photo(9849651, 1200, 750) },
  { slug: 'blazer-fit', title: 'راهنمای اندازه و فیت بلیزر', excerpt: 'فیت درست بلیزر از سرشانه آغاز می‌شود و در طول آستین و آزادی سینه کامل می‌شود.', body: 'در انتخاب بلیزر ابتدا سرشانه را بررسی کنید: درز آستین باید نزدیک انتهای شانه بنشیند. دکمه را ببندید و مطمئن شوید پارچه روی سینه کشیده نمی‌شود. آستین بهتر است بخشی از سرآستین پیراهن را نشان دهد. اگر بین دو سایز مردد هستید، اندازهٔ مناسب شانه را انتخاب کنید؛ اصلاح قد آستین ساده‌تر از اصلاح سرشانه است.', category: 'راهنمای اندازه', tags: ['بلیزر', 'فیت', 'راهنمای خرید'], cover: photo(8483838, 1200, 750) },
] as const;

export const demoCategoryImages: Record<string, string> = {
  coats: photo(12349052, 900, 700), shirts: photo(8306364, 900, 700),
  trousers: photo(9968536, 900, 700), shoes: photo(18054235, 900, 700),
  knitwear: photo(5788999, 900, 700), accessories: photo(27100523, 900, 700),
};
