import { createHash, randomUUID } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { Config } from './config.js';
import { transaction, type DbPool } from './db.js';
import { principal, requirePermission } from './auth.js';
import { audit } from './operations.js';
import { ApiError, badRequest, notFound } from './errors.js';
import { createObjectStorage } from './storage.js';

const entityType = z.enum(['site','product','category','brand','blog','cms','landing']);
const seoBody = z.object({
  seoTitle: z.string().max(300).default(''), metaDescription: z.string().max(1000).default(''),
  slug: z.string().max(1000).default(''), canonicalUrl: z.string().max(2000).default(''),
  isIndexable: z.boolean().default(true), isFollowable: z.boolean().default(true),
  socialTitle: z.string().max(300).default(''), socialDescription: z.string().max(1000).default(''),
  socialImageUrl: z.string().max(2000).default(''), schemaOverride: z.record(z.string(), z.unknown()).default({}),
});
const redirectBody = z.object({ sourcePath: z.string().startsWith('/').max(2000), targetPath: z.string().startsWith('/').max(2000).nullable(), statusCode: z.union([z.literal(301),z.literal(302),z.literal(410)]), active: z.boolean().default(true) }).refine((v) => v.statusCode === 410 ? v.targetPath === null : !!v.targetPath);
const postBody = z.object({ postType: z.enum(['article','video']), slug: z.string().trim().min(1).max(250).regex(/^[\p{L}\p{N}._-]+$/u), title: z.string().trim().min(1).max(300), excerpt: z.string().max(2000).default(''), body: z.string().max(200000).default(''), coverUrl: z.string().max(2000).default(''), author: z.string().max(200).default(''), category: z.string().max(150).default(''), tags: z.array(z.string().max(100)).max(50).default([]), sourceType: z.enum(['youtube','direct','external']).nullable().default(null), sourceUrl: z.string().max(3000).default(''), durationSeconds: z.number().int().nonnegative().nullable().default(null), seoTitle: z.string().max(300).default(''), seoDescription: z.string().max(1000).default(''), relatedProductIds: z.array(z.uuid()).max(100).default([]), status: z.enum(['draft','published','archived']).default('draft') }).refine((p) => p.postType !== 'video' || (!!p.sourceType && p.sourceUrl.startsWith('https://')), 'ویدیو باید منبع HTTPS داشته باشد.');
const mediaBody = z.object({ mediaType: z.enum(['image','video','pdf']), sourceType: z.enum(['object_storage','youtube','external']), storageKey: z.string().max(1000).default(''), publicUrl: z.url().max(3000), mimeType: z.string().max(150).default(''), byteSize: z.number().int().nonnegative().nullable().default(null), width: z.number().int().positive().nullable().default(null), height: z.number().int().positive().nullable().default(null), durationSeconds: z.number().int().nonnegative().nullable().default(null), altText: z.string().max(500).default(''), title: z.string().max(300).default(''), caption: z.string().max(1000).default(''), fileName: z.string().max(500).default(''), metadata: z.record(z.string(), z.unknown()).default({}) });
const publicUrl = (value: string) => { try { const url = new URL(value); return url.protocol === 'https:'; } catch { return false; } };

export function registerSeoRoutes(app: FastifyInstance, pool: DbPool, config: Config) {
  const objectStorage=createObjectStorage(config);
  app.addHook('onRequest',async(request,reply)=>{
    if(request.method!=='GET'||request.url.startsWith('/api/')||request.url.startsWith('/health/'))return;
    const original=request.url.split('?')[0]||'/';let current=original;let status=301;const visited=new Set<string>();
    for(let hop=0;hop<20;hop++){
      if(visited.has(current)){reply.code(508).send({code:'REDIRECT_LOOP'});return reply;}visited.add(current);
      const match=await pool.query('UPDATE seo_redirects SET hit_count=hit_count+1,updated_at=now() WHERE source_path=$1 AND active RETURNING target_path,status_code',[current]);
      const redirect=match.rows[0];if(!redirect){if(current!==original){reply.code(status).header('Location',current).send();return reply;}return;}
      if(Number(redirect.status_code)===410){reply.code(410).send();return reply;}
      if(hop===0)status=Number(redirect.status_code);if(!redirect.target_path){reply.code(410).send();return reply;}current=String(redirect.target_path);
    }
    reply.code(508).send({code:'REDIRECT_HOP_LIMIT'});return reply;
  });
  app.addHook('onResponse',async(request,reply)=>{
    if(request.method!=='GET'||reply.statusCode!==404||request.url.startsWith('/api/')||request.url.startsWith('/health/'))return;
    const path=(request.url.split('?')[0]||'/').slice(0,2000);const referrer=String(request.headers.referer??'').slice(0,2048);
    await pool.query(`INSERT INTO seo_not_found_hits(path,last_referrer) VALUES($1,$2) ON CONFLICT(path,hit_day) DO UPDATE SET hit_count=seo_not_found_hits.hit_count+1,last_seen_at=now(),last_referrer=EXCLUDED.last_referrer`,[path,referrer]);
  });
  app.get('/api/v1/admin/seo/pages', async (request) => {
    const user = await principal(request,pool,config); requirePermission(user,'seo:read');
    const query=z.object({entityType:entityType.optional(),q:z.string().max(200).optional(),limit:z.coerce.number().int().min(1).max(500).default(200)}).parse(request.query);
    const rows=await pool.query(`SELECT entity_type,entity_key,seo_title,meta_description,slug,canonical_url,is_indexable,is_followable,social_title,social_description,social_image_url,schema_override,version,updated_by,updated_at FROM seo_pages WHERE ($1::text IS NULL OR entity_type=$1) AND ($2::text IS NULL OR entity_key ILIKE '%'||$2||'%' OR seo_title ILIKE '%'||$2||'%') ORDER BY entity_type,entity_key LIMIT $3`,[query.entityType??null,query.q??null,query.limit]);
    return {items:rows.rows};
  });
  app.put('/api/v1/admin/seo/pages/:entityType/:entityKey',async(request)=>{
    const user=await principal(request,pool,config);requirePermission(user,'seo:manage');
    const {entityType:kind,entityKey}=z.object({entityType,entityKey:z.string().min(1).max(300)}).parse(request.params);const body=seoBody.parse(request.body);
    if(body.slug && !body.slug.startsWith('/')) throw badRequest('Slug باید با / شروع شود.');
    if(body.canonicalUrl && !publicUrl(body.canonicalUrl)) throw badRequest('Canonical باید HTTPS معتبر باشد.');
    if(body.socialImageUrl && !publicUrl(body.socialImageUrl)) throw badRequest('آدرس تصویر اجتماعی باید HTTPS باشد.');
    return transaction(pool,async(client)=>{
      const old=await client.query('SELECT * FROM seo_pages WHERE entity_type=$1 AND entity_key=$2 FOR UPDATE',[kind,entityKey]);
      const oldValue=old.rows[0]??null;const version=(Number(oldValue?.version)||0)+1;
      const result=await client.query(`INSERT INTO seo_pages(entity_type,entity_key,seo_title,meta_description,slug,canonical_url,is_indexable,is_followable,social_title,social_description,social_image_url,schema_override,version,updated_by)
        VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
        ON CONFLICT(entity_type,entity_key) DO UPDATE SET seo_title=EXCLUDED.seo_title,meta_description=EXCLUDED.meta_description,slug=EXCLUDED.slug,canonical_url=EXCLUDED.canonical_url,is_indexable=EXCLUDED.is_indexable,is_followable=EXCLUDED.is_followable,social_title=EXCLUDED.social_title,social_description=EXCLUDED.social_description,social_image_url=EXCLUDED.social_image_url,schema_override=EXCLUDED.schema_override,version=EXCLUDED.version,updated_by=EXCLUDED.updated_by,updated_at=now()
        RETURNING *`,[kind,entityKey,body.seoTitle,body.metaDescription,body.slug,body.canonicalUrl,body.isIndexable,body.isFollowable,body.socialTitle,body.socialDescription,body.socialImageUrl,JSON.stringify(body.schemaOverride),version,user.id]);
      await client.query('INSERT INTO seo_page_revisions(id,entity_type,entity_key,version,actor_id,before_value,after_value) VALUES($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),kind,entityKey,version,user.id,oldValue?JSON.stringify(oldValue):null,JSON.stringify(result.rows[0])]);
      await audit(client,user.id,'seo.page.updated','seo_page',`${kind}:${entityKey}`,oldValue,result.rows[0],request.ip);
      if(kind==='product' && oldValue?.slug && oldValue.slug!==body.slug){await client.query(`INSERT INTO seo_redirects(id,source_path,target_path,status_code,created_by) VALUES($1,$2,$3,301,$4) ON CONFLICT(source_path) DO UPDATE SET target_path=EXCLUDED.target_path,status_code=301,active=true,updated_at=now()`,[randomUUID(),oldValue.slug,body.slug,user.id]);}
      return result.rows[0];
    });
  });
  app.get('/api/v1/admin/seo/revisions',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:read');const q=z.object({entityType:entityType.optional(),entityKey:z.string().max(300).optional(),limit:z.coerce.number().int().min(1).max(250).default(100)}).parse(request.query);const rows=await pool.query(`SELECT r.*,u.display_name AS actor_name FROM seo_page_revisions r LEFT JOIN users u ON u.id=r.actor_id WHERE ($1::text IS NULL OR r.entity_type=$1) AND ($2::text IS NULL OR r.entity_key=$2) ORDER BY r.created_at DESC LIMIT $3`,[q.entityType??null,q.entityKey??null,q.limit]);return{items:rows.rows};});
  app.get('/api/v1/admin/seo/redirects',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:redirects');const q=z.object({q:z.string().max(500).optional(),limit:z.coerce.number().int().min(1).max(500).default(200)}).parse(request.query);const rows=await pool.query(`SELECT * FROM seo_redirects WHERE ($1::text IS NULL OR source_path ILIKE '%'||$1||'%' OR target_path ILIKE '%'||$1||'%') ORDER BY created_at DESC LIMIT $2`,[q.q??null,q.limit]);return{items:rows.rows};});
  app.post('/api/v1/admin/seo/redirects',async(request,reply)=>{
    const user=await principal(request,pool,config);requirePermission(user,'seo:redirects');const b=redirectBody.parse(request.body);
    const saved=await transaction(pool,async(client)=>{
      await client.query("SELECT pg_advisory_xact_lock(hashtext('kolbe_seo_redirects'))");
      if(b.targetPath){let current=b.targetPath;const visited=new Set([b.sourcePath]);for(let hop=0;hop<20;hop++){if(visited.has(current))throw badRequest('ریدایرکت حلقه‌ای مجاز نیست.');visited.add(current);const next=await client.query('SELECT target_path,status_code FROM seo_redirects WHERE source_path=$1 AND active',[current]);const row=next.rows[0];if(!row||Number(row.status_code)===410||!row.target_path)break;current=String(row.target_path);if(hop===19)throw badRequest('زنجیره ریدایرکت بیش از حد مجاز است.');}}
      const result=await client.query(`INSERT INTO seo_redirects(id,source_path,target_path,status_code,active,created_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(source_path) DO UPDATE SET target_path=EXCLUDED.target_path,status_code=EXCLUDED.status_code,active=EXCLUDED.active,updated_at=now() RETURNING *`,[randomUUID(),b.sourcePath,b.targetPath,b.statusCode,b.active,user.id]);return result.rows[0];
    });return reply.code(201).send(saved);
  });
  app.delete('/api/v1/admin/seo/redirects/:id',async(request,reply)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:redirects');const{id}=z.object({id:z.uuid()}).parse(request.params);await pool.query('DELETE FROM seo_redirects WHERE id=$1',[id]);return reply.code(204).send();});
  app.get('/api/v1/public/seo/redirect',async(request)=>{const{path}=z.object({path:z.string().startsWith('/').max(2000)}).parse(request.query);const result=await pool.query(`UPDATE seo_redirects SET hit_count=hit_count+1,updated_at=now() WHERE source_path=$1 AND active RETURNING target_path,status_code`,[path]);return result.rows[0]??null;});
  app.get('/api/v1/admin/seo/facets',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:technical');const rows=await pool.query('SELECT * FROM seo_facet_policies ORDER BY facet_key');return{items:rows.rows};});
  app.put('/api/v1/admin/seo/facets/:key',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:technical');const{key}=z.object({key:z.string().min(1).max(100)}).parse(request.params);const b=z.object({isIndexable:z.boolean(),crawlAllowed:z.boolean(),canonicalTarget:z.string().startsWith('/').max(2000)}).parse(request.body);const r=await pool.query(`INSERT INTO seo_facet_policies(facet_key,is_indexable,crawl_allowed,canonical_target,updated_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(facet_key) DO UPDATE SET is_indexable=EXCLUDED.is_indexable,crawl_allowed=EXCLUDED.crawl_allowed,canonical_target=EXCLUDED.canonical_target,updated_by=EXCLUDED.updated_by,updated_at=now() RETURNING *`,[key,b.isIndexable,b.crawlAllowed,b.canonicalTarget,user.id]);return r.rows[0];});
  app.get('/api/v1/admin/seo/settings',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:read');const r=await pool.query('SELECT * FROM seo_site_settings WHERE id=true');return r.rows[0]??null;});
  app.put('/api/v1/admin/seo/settings',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:technical');const b=z.object({robotsText:z.string().max(20000),crawlSchedule:z.enum(['manual','daily','weekly']),organizationSchema:z.record(z.string(),z.unknown()),merchantFields:z.record(z.string(),z.unknown())}).parse(request.body);const r=await pool.query(`UPDATE seo_site_settings SET robots_text=$1,crawl_schedule=$2,organization_schema=$3,merchant_fields=$4,updated_by=$5,updated_at=now() WHERE id=true RETURNING *`,[b.robotsText,b.crawlSchedule,JSON.stringify(b.organizationSchema),JSON.stringify(b.merchantFields),user.id]);return r.rows[0];});
  app.post('/api/v1/admin/seo/crawls',async(request,reply)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:technical');const runId=randomUUID();await pool.query(`INSERT INTO seo_crawl_runs(id,started_by,source,status) VALUES($1,$2,'manual','running')`,[runId,user.id]);try{
    const pages=await pool.query(`SELECT p.id::text AS entity_key,'product' AS entity_type,'/product/'||p.id::text AS url,p.name,p.description,p.metadata,s.seo_title,s.meta_description,s.canonical_url,s.is_indexable FROM products p LEFT JOIN seo_pages s ON s.entity_type='product' AND s.entity_key=p.id::text WHERE p.status='published' UNION ALL SELECT e.id::text,'blog','/journal/'||e.slug,e.title,e.excerpt,'{}'::jsonb,s.seo_title,s.meta_description,s.canonical_url,s.is_indexable FROM editorial_posts e LEFT JOIN seo_pages s ON s.entity_type='blog' AND s.entity_key=e.id::text WHERE e.status='published'`);
    const issues:{severity:string;code:string;url:string;details:Record<string,unknown>}[]=[];const titleSeen=new Map<string,string>();for(const p of pages.rows){const title=String(p.seo_title||p.name||'').trim();const desc=String(p.meta_description||p.description||'').trim();if(!title)issues.push({severity:'error',code:'missing_title',url:p.url,details:{}});else if(titleSeen.has(title))issues.push({severity:'warning',code:'duplicate_title',url:p.url,details:{duplicateOf:titleSeen.get(title)}});else titleSeen.set(title,p.url);if(!desc)issues.push({severity:'warning',code:'missing_description',url:p.url,details:{}});if(p.canonical_url&&!publicUrl(p.canonical_url))issues.push({severity:'error',code:'invalid_canonical',url:p.url,details:{value:p.canonical_url}});if(p.is_indexable===false)continue;}
    await transaction(pool,async(client)=>{for(const issue of issues)await client.query('INSERT INTO seo_crawl_issues(id,run_id,severity,issue_code,page_url,details) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),runId,issue.severity,issue.code,issue.url,JSON.stringify(issue.details)]);await client.query(`UPDATE seo_crawl_runs SET status='completed',completed_at=now(),summary=$2 WHERE id=$1`,[runId,JSON.stringify({pages:pages.rowCount,issues:issues.length})]);});return reply.code(201).send({id:runId,status:'completed',pages:pages.rowCount,issues});
  }catch(error){await pool.query(`UPDATE seo_crawl_runs SET status='failed',completed_at=now(),error=$2 WHERE id=$1`,[runId,error instanceof Error?error.message:'unknown']);throw error;}});
  app.get('/api/v1/admin/seo/crawls',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:technical');const rows=await pool.query(`SELECT r.*, (SELECT count(*)::int FROM seo_crawl_issues i WHERE i.run_id=r.id) AS issue_count FROM seo_crawl_runs r ORDER BY started_at DESC LIMIT 100`);return{items:rows.rows};});
  app.get('/api/v1/admin/seo/crawls/:id/issues',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:technical');const{id}=z.object({id:z.uuid()}).parse(request.params);const rows=await pool.query('SELECT * FROM seo_crawl_issues WHERE run_id=$1 ORDER BY severity,issue_code',[id]);return{items:rows.rows};});
  app.get('/api/v1/admin/seo/not-found',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:technical');const q=z.object({limit:z.coerce.number().int().min(1).max(500).default(100)}).parse(request.query);const rows=await pool.query('SELECT path,hit_day,hit_count,first_seen_at,last_seen_at,last_referrer FROM seo_not_found_hits ORDER BY hit_day DESC,hit_count DESC LIMIT $1',[q.limit]);return{items:rows.rows};});
  app.get('/api/v1/admin/search/synonyms',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'search:manage');const rows=await pool.query('SELECT phrase,replacement,active,updated_by,updated_at FROM search_synonyms ORDER BY phrase');return{items:rows.rows};});
  app.put('/api/v1/admin/search/synonyms/:phrase',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'search:manage');const{phrase}=z.object({phrase:z.string().trim().min(1).max(200)}).parse(request.params);const b=z.object({replacement:z.string().trim().min(1).max(200),active:z.boolean().default(true)}).parse(request.body);const r=await pool.query(`INSERT INTO search_synonyms(phrase,replacement,active,updated_by) VALUES($1,$2,$3,$4) ON CONFLICT(phrase) DO UPDATE SET replacement=EXCLUDED.replacement,active=EXCLUDED.active,updated_by=EXCLUDED.updated_by,updated_at=now() RETURNING *`,[phrase.normalize('NFKC').toLowerCase(),b.replacement,b.active,user.id]);return r.rows[0];});
  app.delete('/api/v1/admin/search/synonyms/:phrase',async(request,reply)=>{const user=await principal(request,pool,config);requirePermission(user,'search:manage');const{phrase}=z.object({phrase:z.string().max(200)}).parse(request.params);await pool.query('DELETE FROM search_synonyms WHERE phrase=$1',[phrase]);return reply.code(204).send();});
  app.get('/api/v1/admin/search/analytics',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'search:analytics');await pool.query('DELETE FROM search_metrics WHERE expires_at<=now()');const q=z.object({zeroResult:z.coerce.boolean().optional(),limit:z.coerce.number().int().min(1).max(500).default(100)}).parse(request.query);const rows=await pool.query(`SELECT normalized_query,metric_day,search_count,last_result_count,click_count,conversion_count,zero_result,last_seen_at FROM search_metrics WHERE ($1::boolean IS NULL OR zero_result=$1) ORDER BY metric_day DESC,search_count DESC LIMIT $2`,[q.zeroResult??null,q.limit]);return{items:rows.rows};});
  app.post('/api/v1/public/search/metrics',{config:{rateLimit:{max:120,timeWindow:'1 minute'}}},async(request)=>{const b=z.object({query:z.string().trim().min(1).max(200),event:z.enum(['search','click','conversion']),resultCount:z.number().int().min(0).max(100000).default(0)}).parse(request.body);const normalized=b.query.normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim();const hash=createHash('sha256').update(normalized).digest('hex');await pool.query('DELETE FROM search_metrics WHERE expires_at<=now()');await pool.query(`INSERT INTO search_metrics(query_hash,normalized_query,metric_day,search_count,last_result_count,click_count,conversion_count,zero_result,expires_at) VALUES($1,$2,CURRENT_DATE,$3,$4,$5,$6,$7,now()+interval '30 days') ON CONFLICT(query_hash,metric_day) DO UPDATE SET search_count=search_metrics.search_count+EXCLUDED.search_count,last_result_count=CASE WHEN EXCLUDED.search_count>0 THEN EXCLUDED.last_result_count ELSE search_metrics.last_result_count END,click_count=search_metrics.click_count+EXCLUDED.click_count,conversion_count=search_metrics.conversion_count+EXCLUDED.conversion_count,zero_result=CASE WHEN EXCLUDED.search_count>0 THEN EXCLUDED.zero_result ELSE search_metrics.zero_result END,last_seen_at=now(),expires_at=now()+interval '30 days'`,[hash,normalized,b.event==='search'?1:0,b.resultCount,b.event==='click'?1:0,b.event==='conversion'?1:0,b.event==='search'&&b.resultCount===0]);return{ok:true};});
  const sitemapHandler=async(_request:FastifyRequest,reply:FastifyReply)=>{const r=await pool.query(`SELECT url FROM (
    SELECT COALESCE(NULLIF(s.canonical_url,''),'https://kolbe.ir'||COALESCE(NULLIF(s.slug,''),'/product/'||p.id::text)) AS url FROM products p LEFT JOIN seo_pages s ON s.entity_type='product' AND s.entity_key=p.id::text WHERE p.status='published' AND p.supplier_id IS NULL AND COALESCE(s.is_indexable,true)
    UNION ALL SELECT COALESCE(NULLIF(s.canonical_url,''),'https://kolbe.ir'||COALESCE(NULLIF(s.slug,''),'/journal/'||e.slug)) FROM editorial_posts e LEFT JOIN seo_pages s ON s.entity_type='blog' AND s.entity_key=e.id::text WHERE e.status='published' AND COALESCE(s.is_indexable,true)
    UNION ALL SELECT COALESCE(NULLIF(canonical_url,''),'https://kolbe.ir'||slug) FROM seo_pages WHERE entity_type IN ('site','category','brand','cms','landing') AND is_indexable AND slug<>''
    ) AS urls WHERE url LIKE 'https://kolbe.ir/%' ORDER BY url`);const xml=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${r.rows.map((x)=>`<url><loc>${String(x.url).replace(/&/g,'&amp;').replace(/</g,'&lt;')}</loc></url>`).join('')}</urlset>`;return reply.type('application/xml; charset=utf-8').header('Cache-Control','public, max-age=300').send(xml);};
  const robotsHandler=async(_request:FastifyRequest,reply:FastifyReply)=>{const r=await pool.query('SELECT robots_text FROM seo_site_settings WHERE id=true');return reply.type('text/plain; charset=utf-8').header('Cache-Control','public, max-age=300').send(`${r.rows[0]?.robots_text??'User-agent: *\nAllow: /'}\nSitemap: https://kolbe.ir/sitemap.xml`);};
  app.get('/api/v1/public/sitemap.xml',sitemapHandler);app.get('/sitemap.xml',sitemapHandler);
  app.get('/api/v1/public/robots.txt',robotsHandler);app.get('/robots.txt',robotsHandler);

  app.get('/api/v1/public/editorial',async(request)=>{const q=z.object({type:z.enum(['article','video']).optional(),limit:z.coerce.number().int().min(1).max(100).default(30)}).parse(request.query);const rows=await pool.query(`SELECT id,post_type,slug,title,excerpt,cover_url,author,category,tags,source_type,source_url,duration_seconds,seo_title,seo_description,related_product_ids,published_at FROM editorial_posts WHERE status='published' AND ($1::text IS NULL OR post_type=$1) AND (published_at IS NULL OR published_at<=now()) ORDER BY published_at DESC NULLS LAST,created_at DESC LIMIT $2`,[q.type??null,q.limit]);return{items:rows.rows};});
  app.get('/api/v1/public/editorial/:slug',async(request)=>{const{slug}=z.object({slug:z.string().max(250)}).parse(request.params);const r=await pool.query(`SELECT id,post_type,slug,title,excerpt,body,cover_url,author,category,tags,source_type,source_url,duration_seconds,seo_title,seo_description,related_product_ids,published_at FROM editorial_posts WHERE slug=$1 AND status='published' AND (published_at IS NULL OR published_at<=now())`,[slug]);if(!r.rowCount)throw notFound();return r.rows[0];});
  app.get('/api/v1/admin/editorial',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'content:manage');const q=z.object({type:z.enum(['article','video']).optional(),status:z.enum(['draft','published','archived']).optional(),limit:z.coerce.number().int().min(1).max(250).default(100)}).parse(request.query);const rows=await pool.query(`SELECT * FROM editorial_posts WHERE ($1::text IS NULL OR post_type=$1) AND ($2::text IS NULL OR status=$2) ORDER BY updated_at DESC LIMIT $3`,[q.type??null,q.status??null,q.limit]);return{items:rows.rows};});
  app.post('/api/v1/admin/editorial',async(request,reply)=>{const user=await principal(request,pool,config);requirePermission(user,'content:manage');const b=postBody.parse(request.body);if(b.coverUrl&&!publicUrl(b.coverUrl))throw badRequest('تصویر شاخص باید URL امن HTTPS باشد.');if(b.sourceType==='youtube'&&!isYoutubeUrl(b.sourceUrl))throw badRequest('نشانی یوتیوب معتبر نیست.');const id=randomUUID();const r=await pool.query(`INSERT INTO editorial_posts(id,post_type,slug,title,excerpt,body,cover_url,author,category,tags,source_type,source_url,duration_seconds,seo_title,seo_description,related_product_ids,status,published_at,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,CASE WHEN $17='published' THEN now() ELSE NULL END,$18,$18) RETURNING *`,[id,b.postType,b.slug,b.title,b.excerpt,b.body,b.coverUrl,b.author,b.category,JSON.stringify(b.tags),b.sourceType,b.sourceUrl,b.durationSeconds,b.seoTitle,b.seoDescription,b.relatedProductIds,b.status,user.id]);return reply.code(201).send(r.rows[0]);});
  app.put('/api/v1/admin/editorial/:id',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'content:manage');const{id}=z.object({id:z.uuid()}).parse(request.params);const b=postBody.parse(request.body);if(b.coverUrl&&!publicUrl(b.coverUrl))throw badRequest('تصویر شاخص باید URL امن HTTPS باشد.');if(b.sourceType==='youtube'&&!isYoutubeUrl(b.sourceUrl))throw badRequest('نشانی یوتیوب معتبر نیست.');const r=await pool.query(`UPDATE editorial_posts SET post_type=$2,slug=$3,title=$4,excerpt=$5,body=$6,cover_url=$7,author=$8,category=$9,tags=$10,source_type=$11,source_url=$12,duration_seconds=$13,seo_title=$14,seo_description=$15,related_product_ids=$16,status=$17,published_at=CASE WHEN $17='published' THEN COALESCE(published_at,now()) ELSE NULL END,updated_by=$18,version=version+1,updated_at=now() WHERE id=$1 RETURNING *`,[id,b.postType,b.slug,b.title,b.excerpt,b.body,b.coverUrl,b.author,b.category,JSON.stringify(b.tags),b.sourceType,b.sourceUrl,b.durationSeconds,b.seoTitle,b.seoDescription,b.relatedProductIds,b.status,user.id]);if(!r.rowCount)throw notFound();return r.rows[0];});
  app.delete('/api/v1/admin/editorial/:id',async(request,reply)=>{const user=await principal(request,pool,config);requirePermission(user,'content:manage');const{id}=z.object({id:z.uuid()}).parse(request.params);await pool.query('DELETE FROM editorial_posts WHERE id=$1',[id]);return reply.code(204).send();});
  app.get('/api/v1/public/media/:id',async(request)=>{const{id}=z.object({id:z.uuid()}).parse(request.params);const r=await pool.query('SELECT id,media_type,source_type,public_url,mime_type,width,height,duration_seconds,alt_text,title,caption,file_name,metadata,processing_status FROM media_assets WHERE id=$1',[id]);if(!r.rowCount)throw notFound();return r.rows[0];});
  app.get('/api/v1/admin/media',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'media:manage');const q=z.object({q:z.string().max(200).optional(),type:z.enum(['image','video','pdf']).optional(),limit:z.coerce.number().int().min(1).max(250).default(100)}).parse(request.query);const r=await pool.query(`SELECT * FROM media_assets WHERE ($1::text IS NULL OR media_type=$1) AND ($2::text IS NULL OR title ILIKE '%'||$2||'%' OR alt_text ILIKE '%'||$2||'%' OR file_name ILIKE '%'||$2||'%' OR metadata::text ILIKE '%'||$2||'%') ORDER BY created_at DESC LIMIT $3`,[q.type??null,q.q??null,q.limit]);return{items:r.rows};});
  app.post('/api/v1/admin/media',async(request,reply)=>{const user=await principal(request,pool,config);requirePermission(user,'media:manage');const b=mediaBody.parse(request.body);if(!publicUrl(b.publicUrl))throw badRequest('URL رسانه باید HTTPS باشد.');if(b.sourceType==='youtube'&&!isYoutubeUrl(b.publicUrl))throw badRequest('URL یوتیوب معتبر نیست.');if(b.sourceType==='object_storage'&&!b.storageKey)throw badRequest('Storage key لازم است.');const r=await pool.query(`INSERT INTO media_assets(id,media_type,source_type,storage_key,public_url,mime_type,byte_size,width,height,duration_seconds,alt_text,title,caption,file_name,metadata,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *`,[randomUUID(),b.mediaType,b.sourceType,b.storageKey,b.publicUrl,b.mimeType,b.byteSize,b.width,b.height,b.durationSeconds,b.altText,b.title,b.caption,b.fileName,JSON.stringify(b.metadata),user.id]);return reply.code(201).send(r.rows[0]);});
  app.patch('/api/v1/admin/media/:id',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'media:manage');const{id}=z.object({id:z.uuid()}).parse(request.params);const b=z.object({altText:z.string().max(500).optional(),title:z.string().max(300).optional(),caption:z.string().max(1000).optional(),metadata:z.record(z.string(),z.unknown()).optional()}).parse(request.body);const r=await pool.query(`UPDATE media_assets SET alt_text=COALESCE($2,alt_text),title=COALESCE($3,title),caption=COALESCE($4,caption),metadata=COALESCE($5,metadata),updated_at=now() WHERE id=$1 RETURNING *`,[id,b.altText??null,b.title??null,b.caption??null,b.metadata?JSON.stringify(b.metadata):null]);if(!r.rowCount)throw notFound();return r.rows[0];});
  app.post('/api/v1/admin/media/upload-intents',async(request,reply)=>{const user=await principal(request,pool,config);requirePermission(user,'media:manage');if(!objectStorage)throw new ApiError(503,'STORAGE_UNAVAILABLE','اتصال Object Storage تنظیم نشده است.');const b=z.object({mediaType:z.enum(['image','video','pdf']),fileName:z.string().trim().min(1).max(240),mimeType:z.string().min(1).max(150),byteSize:z.number().int().positive()}).parse(request.body);const max=b.mediaType==='video'?500*1024*1024:25*1024*1024;const allow=b.mediaType==='image'?/^image\/(jpeg|png|webp|avif|gif)$/.test(b.mimeType):b.mediaType==='video'?/^video\/(mp4|webm|quicktime)$/.test(b.mimeType):b.mimeType==='application/pdf';if(!allow||b.byteSize>max)throw badRequest('نوع یا اندازه فایل مجاز نیست.');const safeName=b.fileName.normalize('NFKC').replace(/[^\p{L}\p{N}._-]+/gu,'_').slice(-160);const id=randomUUID();const key=`${b.mediaType}/${user.id}/${id}-${safeName}`;const expiresAt=new Date(Date.now()+5*60*1000);const uploadUrl=await objectStorage.signPut(key,b.mimeType);await pool.query('INSERT INTO media_upload_intents(id,actor_id,storage_key,mime_type,byte_size,expires_at) VALUES($1,$2,$3,$4,$5,$6)',[id,user.id,key,b.mimeType,b.byteSize,expiresAt]);return reply.code(201).send({id,uploadUrl,method:'PUT',headers:{'Content-Type':b.mimeType},publicUrl:`${objectStorage.publicBase}/${key.split('/').map(encodeURIComponent).join('/')}`,expiresAt:expiresAt.toISOString()});});
  app.post('/api/v1/admin/media/upload-intents/:id/complete',async(request,reply)=>{const user=await principal(request,pool,config);requirePermission(user,'media:manage');if(!objectStorage)throw new ApiError(503,'STORAGE_UNAVAILABLE','اتصال Object Storage تنظیم نشده است.');const{id}=z.object({id:z.uuid()}).parse(request.params);const intent=await pool.query(`SELECT * FROM media_upload_intents WHERE id=$1 AND actor_id=$2 AND completed_at IS NULL AND expires_at>now()`,[id,user.id]);if(!intent.rowCount)throw notFound();const row=intent.rows[0];let head;try{head=await objectStorage.head(row.storage_key);}catch{throw badRequest('فایل در فضای ذخیره‌سازی پیدا نشد.');}if(head.size!==Number(row.byte_size)||head.contentType!==row.mime_type)throw badRequest('اندازه یا نوع محتوای بارگذاری‌شده با مجوز آپلود تطبیق ندارد.');const mime=String(row.mime_type);const mediaType=mime.startsWith('image/')?'image':mime.startsWith('video/')?'video':'pdf';const publicUrl=`${objectStorage.publicBase}/${String(row.storage_key).split('/').map(encodeURIComponent).join('/')}`;const result=await transaction(pool,async(client)=>{const media=await client.query(`INSERT INTO media_assets(id,media_type,source_type,storage_key,public_url,mime_type,byte_size,processing_status,created_by) VALUES($1,$2,'object_storage',$3,$4,$5,$6,$7,$8) RETURNING *`,[randomUUID(),mediaType,row.storage_key,publicUrl,mime,row.byte_size,mediaType==='video'?'pending':'ready',user.id]);await client.query('UPDATE media_upload_intents SET completed_at=now() WHERE id=$1',[id]);return media.rows[0];});return reply.code(201).send(result);});
  app.get('/api/v1/admin/products/:id/media',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'media:manage');const{id}=z.object({id:z.uuid()}).parse(request.params);const rows=await pool.query(`SELECT pm.id,pm.variant_id,pm.purpose,pm.position,ma.* FROM product_media pm JOIN media_assets ma ON ma.id=pm.media_asset_id WHERE pm.product_id=$1 ORDER BY pm.variant_id NULLS FIRST,pm.position,ma.created_at`,[id]);return{items:rows.rows};});
  app.post('/api/v1/admin/products/:id/media',async(request,reply)=>{const user=await principal(request,pool,config);requirePermission(user,'media:manage');const{ id:productId }=z.object({id:z.uuid()}).parse(request.params);const b=z.object({mediaAssetId:z.uuid(),variantId:z.uuid().nullable().default(null),purpose:z.string().min(1).max(100).default('gallery'),position:z.number().int().min(0).max(10000).default(0)}).parse(request.body);const result=await transaction(pool,async(client)=>{const p=await client.query('SELECT id FROM products WHERE id=$1',[productId]);if(!p.rowCount)throw notFound();if(b.variantId){const v=await client.query('SELECT id FROM product_variants WHERE id=$1 AND product_id=$2',[b.variantId,productId]);if(!v.rowCount)throw badRequest('واریانت به این محصول تعلق ندارد.');}const m=await client.query('SELECT id FROM media_assets WHERE id=$1 AND processing_status IN (\'ready\',\'pending\')',[b.mediaAssetId]);if(!m.rowCount)throw notFound();return client.query(`INSERT INTO product_media(id,product_id,variant_id,media_asset_id,purpose,position) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING RETURNING *`,[randomUUID(),productId,b.variantId,b.mediaAssetId,b.purpose,b.position]);});return reply.code(201).send(result.rows[0]??{ok:true});});
  app.delete('/api/v1/admin/products/:id/media/:mediaId',async(request,reply)=>{const user=await principal(request,pool,config);requirePermission(user,'media:manage');const{ id:productId,mediaId }=z.object({id:z.uuid(),mediaId:z.uuid()}).parse(request.params);await pool.query('DELETE FROM product_media WHERE product_id=$1 AND id=$2',[productId,mediaId]);return reply.code(204).send();});
  app.get('/api/v1/public/products/:id/media',async(request)=>{const{id}=z.object({id:z.uuid()}).parse(request.params);const rows=await pool.query(`SELECT ma.id,ma.media_type,ma.public_url,ma.alt_text,ma.title,ma.caption,ma.width,ma.height,ma.duration_seconds,pm.variant_id,pm.purpose,pm.position FROM product_media pm JOIN media_assets ma ON ma.id=pm.media_asset_id JOIN products p ON p.id=pm.product_id WHERE pm.product_id=$1 AND p.status='published' AND ma.processing_status='ready' ORDER BY pm.variant_id NULLS FIRST,pm.position`,[id]);return{items:rows.rows};});
  app.get('/api/v1/admin/seo/integration',async(request)=>{const user=await principal(request,pool,config);requirePermission(user,'seo:integrations');const r=await pool.query('SELECT provider,status,property_url,last_synced_at,last_error,updated_at FROM seo_integration_status');return{items:r.rows.map((row)=>row.provider==='object_storage'?{...row,status:objectStorage?'configured':'not_configured'}:row)};});
}
function isYoutubeUrl(value:string){try{const u=new URL(value);const host=u.hostname.toLowerCase().replace(/^www\./,'');if(!['youtube.com','m.youtube.com','youtu.be','youtube-nocookie.com'].includes(host))return false;const id=host==='youtu.be'?u.pathname.split('/').filter(Boolean)[0]:u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).at(-1);return !!id&&/^[\w-]{11}$/.test(id);}catch{return false;}}
