import { useEffect, useState } from 'react';
import { studioApi, type HeaderConfig, type FooterConfig } from '../data/experience-api';
import { Btn, Card, Empty, ErrorState, Field, Input, LoadingState, Segmented, Textarea } from '../components/primitives';
import { TargetInput, loadPickers, type PickerData } from './admin-section-editor';
import { PersianDatePicker } from '../components/persian-date-picker';
import { cmsError } from './cms-api';
export function CmsGlobalContent({flash}:{flash:(m:string)=>void}) {
  const [tab,setTab]=useState<'header'|'footer'|'announcements'>('header');
  const [header,setHeader]=useState<HeaderConfig|null>(null),[footer,setFooter]=useState<FooterConfig|null>(null),[announcements,setAnnouncements]=useState<Awaited<ReturnType<typeof studioApi.announcements>>['items']|null>(null);
  const [annEdit,setAnnEdit]=useState<Awaited<ReturnType<typeof studioApi.announcements>>['items'][number]|null>(null),[start,setStart]=useState<string|null>(null),[end,setEnd]=useState<string|null>(null);
  const [pickers,setPickers]=useState<PickerData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[title,setTitle]=useState(''),[text,setText]=useState(''),[target,setTarget]=useState('shop');
  const load=()=>{setError('');void Promise.all([studioApi.layout(),studioApi.announcements(),loadPickers()]).then(([l,a,p])=>{setHeader(l.header);setFooter(l.footer);setAnnouncements(a.items);setPickers(p);}).catch(e=>setError(cmsError(e)));};
  useEffect(load,[]);
  const run=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();flash('محتوای سراسری ذخیره و در سایت اعمال شد');load();}catch(e){setError(cmsError(e));}finally{setBusy(false);}};
  return <div className="space-y-4"><Segmented options={[{v:'header' as const,label:'هدر'},{v:'footer' as const,label:'فوتر'},{v:'announcements' as const,label:'نوار اعلان'}]} value={tab} onChange={setTab}/><p className="text-sm text-[var(--kv-muted)]">این محتوا در سراسر سایت استفاده می‌شود. «ذخیره و اعمال در سایت» تغییرات را بلافاصله فعال می‌کند.</p>
    {!!pickers?.errors.length&&<ErrorState message="برخی مقصدها بارگذاری نشدند" onRetry={()=>void loadPickers().then(setPickers)}/>}
    {error&&<ErrorState message={error} onRetry={load}/>}
    {!header||!footer||!announcements?<LoadingState/>:<>
      {tab==='header'&&<Card className="space-y-4 p-4"><h3 className="font-bold">هدر سایت</h3><div className="grid gap-3 sm:grid-cols-2"><Field label="عنوان لوگو"><Input value={header.logoText} onChange={logoText=>setHeader({...header,logoText})}/></Field><Field label="زیرعنوان لوگو"><Input value={header.logoSubtext} onChange={logoSubtext=>setHeader({...header,logoSubtext})}/></Field><Field label="متن دکمه"><Input value={header.ctaLabel} onChange={ctaLabel=>setHeader({...header,ctaLabel})}/></Field><TargetInput label="مقصد دکمه" value={header.ctaTarget} onChange={v=>setHeader({...header,ctaTarget:String(v??'')})} pickers={pickers}/></div>
        <label className="flex gap-2 text-sm"><input type="checkbox" checked={!!header.ctaEnabled} onChange={e=>setHeader({...header,ctaEnabled:e.target.checked})}/>نمایش دکمه هدر</label><h4 className="text-sm font-bold">پیوندهای ناوبری</h4>
        {header.menus.map((m,i)=><div key={m.id} className="grid gap-2 border-b border-[var(--kv-line)] py-3 sm:grid-cols-2"><Field label="عنوان پیوند"><Input value={m.label} onChange={label=>setHeader({...header,menus:header.menus.map((x,j)=>j===i?{...x,label}:x)})}/></Field><TargetInput label="مقصد" value={m.target} onChange={v=>setHeader({...header,menus:header.menus.map((x,j)=>j===i?{...x,target:String(v??'')}:x)})} pickers={pickers}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={m.active} onChange={e=>setHeader({...header,menus:header.menus.map((x,j)=>j===i?{...x,active:e.target.checked}:x)})}/>نمایش پیوند</label><Btn size="sm" variant="ghost" onClick={()=>setHeader({...header,menus:header.menus.filter((_,j)=>j!==i)})}>حذف پیوند</Btn></div>)}<Btn size="sm" variant="soft" onClick={()=>setHeader({...header,menus:[...header.menus,{id:crypto.randomUUID(),label:'پیوند جدید',target:'shop',order:header.menus.length,active:true}]})}>+ پیوند</Btn><div><Btn variant="accent" disabled={busy} onClick={()=>void run(()=>studioApi.saveLayout('global_header',header))}>{busy?'در حال ذخیره…':'ذخیره و اعمال در سایت'}</Btn></div>
      </Card>}
      {tab==='footer'&&<Card className="space-y-4 p-4"><h3 className="font-bold">فوتر سایت</h3><Field label="عنوان برند"><Input value={footer.brandTitle} onChange={brandTitle=>setFooter({...footer,brandTitle})}/></Field><Field label="زیرعنوان"><Input value={footer.brandSubtitle} onChange={brandSubtitle=>setFooter({...footer,brandSubtitle})}/></Field><Field label="توضیحات برند"><Textarea value={footer.brandDescription} onChange={brandDescription=>setFooter({...footer,brandDescription})}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="تلفن"><Input value={footer.contact.phone} onChange={phone=>setFooter({...footer,contact:{...footer.contact,phone}})}/></Field><Field label="ایمیل"><Input value={footer.contact.email} onChange={email=>setFooter({...footer,contact:{...footer.contact,email}})}/></Field><Field label="نشانی"><Input value={footer.contact.address} onChange={address=>setFooter({...footer,contact:{...footer.contact,address}})}/></Field><Field label="متن حقوق نشر"><Input value={footer.copyright} onChange={copyright=>setFooter({...footer,copyright})}/></Field></div>
        {footer.columns.map((c,i)=><fieldset key={i} className="space-y-3 rounded-lg border border-[var(--kv-line)] p-3"><Field label="عنوان گروه"><Input value={c.title} onChange={title=>setFooter({...footer,columns:footer.columns.map((x,j)=>i===j?{...x,title}:x)})}/></Field>{c.links.map((l,j)=><div key={j} className="grid gap-2 sm:grid-cols-2"><Field label="عنوان پیوند"><Input value={l.label} onChange={label=>setFooter({...footer,columns:footer.columns.map((x,k)=>k===i?{...x,links:x.links.map((link,n)=>n===j?{...link,label}:link)}:x)})}/></Field><TargetInput label="مقصد" value={l.target} onChange={v=>setFooter({...footer,columns:footer.columns.map((x,k)=>k===i?{...x,links:x.links.map((link,n)=>n===j?{...link,target:String(v??'')}:link)}:x)})} pickers={pickers}/></div>)}</fieldset>)}<Btn variant="accent" disabled={busy} onClick={()=>void run(()=>studioApi.saveLayout('global_footer',footer))}>{busy?'در حال ذخیره…':'ذخیره و اعمال در سایت'}</Btn>
      </Card>}
      {tab==='announcements'&&<div className="space-y-3">{!announcements.length&&<Empty title="اعلانی ثبت نشده" desc="یک پیام سراسری برای سایت ایجاد کنید."/>}{announcements.map(a=><Card key={a.id} className="flex flex-wrap items-center gap-3 p-4"><div className="min-w-0 flex-1"><b className="break-words text-sm">{a.title}</b><p className="break-words text-sm">{a.messages.map(m=>m.text).join(' · ')}</p><span className="text-xs">{a.active?'فعال':'غیرفعال'}</span></div><Btn size="sm" disabled={busy} variant="soft" onClick={()=>{setAnnEdit(a);setTitle(a.title);setText(a.messages[0]?.text??'');setTarget(a.messages[0]?.link??'shop');setStart(a.starts_at);setEnd(a.ends_at);}}>ویرایش</Btn><Btn size="sm" disabled={busy} variant="soft" onClick={()=>void run(()=>studioApi.updateAnnouncement(a.id,{active:!a.active}))}>{a.active?'غیرفعال‌سازی':'فعال‌سازی'}</Btn></Card>)}<Card className="space-y-3 p-4"><h3 className="font-bold">{annEdit?'ویرایش اعلان':'اعلان جدید'}</h3><Field label="عنوان داخلی"><Input value={title} onChange={setTitle}/></Field><Field label="متن اعلان"><Textarea value={text} onChange={setText}/></Field><TargetInput label="مقصد" value={target} onChange={v=>setTarget(String(v??'shop'))} pickers={pickers}/><PersianDatePicker label="شروع نمایش (اختیاری)" withTime value={start} onChange={setStart}/><PersianDatePicker label="پایان نمایش (اختیاری)" withTime value={end} onChange={setEnd}/><Btn variant="accent" disabled={busy||!title.trim()||!text.trim()} onClick={()=>void run(async()=>{if(annEdit)await studioApi.updateAnnouncement(annEdit.id,{title,messages:[{...annEdit.messages[0],text,link:target},...annEdit.messages.slice(1)],startsAt:start,endsAt:end});else await studioApi.createAnnouncement({title,startsAt:start,endsAt:end,messages:[{text,link:target}],mode:'static',priority:0,active:true,bindingType:'none',bindingId:null,style:{backgroundColor:'#1B2A4A',textColor:'#FFFFFF',dismissible:true}});setTitle('');setText('');setAnnEdit(null);setStart(null);setEnd(null);})}>{busy?'در حال ذخیره…':'ذخیره و اعمال در سایت'}</Btn></Card></div>}
    </>}
  </div>;
}
