import { useEffect, useState } from 'react';
import { apiClient } from '../data/api';
import { Btn, Empty, ErrorState, Field, Input, LoadingState, Select, Textarea, WorkspaceModal } from '../components/primitives';
import { formatPersianDateTime } from '../data/persian-date';
import { cmsError, PAGE_STATUS } from './cms-api';
import { FieldInput, loadPickers, type PickerData } from './admin-section-editor';
type Post={id:string;post_type:'article'|'video';slug:string;title:string;excerpt:string;body:string;cover_url:string;author:string;category:string;tags:string[];source_type:'youtube'|'direct'|'external'|null;source_url:string;duration_seconds:number|null;seo_title:string;seo_description:string;related_product_ids:string[];status:'draft'|'published'|'archived';version:number;updated_at:string;published_snapshot:unknown;publication_enabled?:boolean};
const emptyPost=():Post=>({id:'',post_type:'article',slug:'',title:'',excerpt:'',body:'',cover_url:'',author:'',category:'',tags:[],source_type:null,source_url:'',duration_seconds:null,seo_title:'',seo_description:'',related_product_ids:[],status:'draft',version:1,updated_at:'',published_snapshot:null});
export function CmsJournal({flash,initialCreate=false}:{flash:(m:string)=>void;initialCreate?:boolean}) {
  const [offset,setOffset]=useState(0),[total,setTotal]=useState(0);
  const [posts,setPosts]=useState<Post[]|null>(null),[error,setError]=useState(''),[q,setQ]=useState(''),[status,setStatus]=useState('همه مطالب');
  const [post,setPost]=useState<Post|null>(initialCreate?emptyPost():null),[busy,setBusy]=useState(false),[saveError,setSaveError]=useState(''),[confirm,setConfirm]=useState(false),[pickers,setPickers]=useState<PickerData|null>(null);
  const load=()=>{setError('');void apiClient.get<{items:Post[];total:number}>(`/admin/editorial?limit=25&offset=${offset}&q=${encodeURIComponent(q)}${status==='همه مطالب'?'':`&status=${Object.entries(PAGE_STATUS).find(([,v])=>v===status)?.[0]}`}`).then(r=>{setPosts(r.items);setTotal(r.total);}).catch(e=>setError(cmsError(e)));};
  useEffect(()=>{void loadPickers().then(setPickers).catch(e=>setError(cmsError(e)));},[]);
  useEffect(()=>{const t=window.setTimeout(load,250);return()=>window.clearTimeout(t);},[q,status,offset]);
  const save=async(p:Post,nextStatus:Post['status'])=>{
    setBusy(true);setSaveError('');
    try {const payload={postType:p.post_type,slug:p.slug,title:p.title,excerpt:p.excerpt,body:p.body,coverUrl:p.cover_url,author:p.author,category:p.category,tags:p.tags,sourceType:p.source_type,sourceUrl:p.source_url,durationSeconds:p.duration_seconds,seoTitle:p.seo_title,seoDescription:p.seo_description,relatedProductIds:p.related_product_ids,status:nextStatus,...(p.id?{expectedVersion:p.version}:{})};
      const saved=p.id?await apiClient.put<Post>(`/admin/editorial/${p.id}`,payload):await apiClient.post<Post>('/admin/editorial',payload);
      setPost(saved);setConfirm(false);load();flash(nextStatus==='published'?'مطلب منتشر شد':nextStatus==='archived'?'مطلب بایگانی شد':'پیش‌نویس در سرور ذخیره شد');
    }catch(e){setSaveError(cmsError(e));}finally{setBusy(false);}
  };
  const edit=(p:Post)=>{setPost(p);setSaveError('');setConfirm(false);};
  const visible=posts;
  return <div className="space-y-4">
    <div className="flex flex-wrap gap-3"><div className="min-w-0 flex-1"><Input value={q} onChange={v=>{setQ(v);setOffset(0);}} placeholder="جست‌وجوی مطالب مجله"/></div><Select options={['همه مطالب',...Object.values(PAGE_STATUS).filter(s=>s!=='زمان‌بندی‌شده')]} value={status} onChange={v=>{setStatus(v);setOffset(0);}}/><Btn variant="accent" onClick={()=>edit(emptyPost())}>+ مطلب جدید</Btn></div>
    {!!pickers?.errors.length&&<ErrorState message="فهرست رسانه‌ها کامل بارگذاری نشد" onRetry={()=>void loadPickers().then(setPickers)}/>}
    {error?<ErrorState message={error} onRetry={load}/>:!posts?<LoadingState/>:!visible?.length?<Empty title="مطلبی پیدا نشد" desc="یک مطلب جدید ایجاد کنید یا فیلتر را تغییر دهید."/>:<div className="divide-y divide-[var(--kv-line)] rounded-xl border border-[var(--kv-line)]">{visible.map(p=><article key={p.id} className="flex flex-wrap items-center gap-3 p-4"><div className="min-w-0 flex-1"><b className="break-words text-sm">{p.title}</b><p className="text-xs text-[var(--kv-muted)]">{p.post_type==='video'?'ویدیو':'مقاله'} · {PAGE_STATUS[p.status]}{p.status==='draft'&&p.publication_enabled?' · نسخهٔ قبلی زنده است':''} · {formatPersianDateTime(p.updated_at)}</p></div><Btn size="sm" variant="soft" onClick={()=>edit(p)}>ویرایش</Btn></article>)}</div>}
    {total>25&&<div className="flex items-center gap-3"><Btn size="sm" disabled={offset===0} onClick={()=>setOffset(offset-25)}>قبلی</Btn><span className="text-xs">{Math.floor(offset/25)+1} / {Math.ceil(total/25)}</span><Btn size="sm" disabled={offset+25>=total} onClick={()=>setOffset(offset+25)}>بعدی</Btn></div>}
    <WorkspaceModal open={!!post} onClose={()=>{if(!busy)setPost(null);}} title="نویسندگی مجله" subtitle="ذخیرهٔ پیش‌نویس نسخهٔ زندهٔ قبلی را تغییر نمی‌دهد؛ انتشار صریح لازم است.">
      {post&&<div className="mx-auto max-w-4xl space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="نوع مطلب"><Select options={['مقاله','ویدیو']} value={post.post_type==='video'?'ویدیو':'مقاله'} onChange={label=>edit({...post,post_type:label==='ویدیو'?'video':'article',source_type:label==='ویدیو'?'youtube':null})}/></Field><Field label="عنوان"><Input value={post.title} onChange={title=>setPost({...post,title})}/></Field><Field label="نشانی مطلب"><Input value={post.slug} onChange={slug=>setPost({...post,slug})}/></Field><Field label="نویسنده"><Input value={post.author} onChange={author=>setPost({...post,author})}/></Field><Field label="دستهٔ مجله"><Input value={post.category} onChange={category=>setPost({...post,category})}/></Field><Field label="برچسب‌ها (جداشده با ویرگول)"><Input value={post.tags.join(',')} onChange={tags=>setPost({...post,tags:tags.split(',')})}/></Field></div>
        <FieldInput field={{key:'cover',type:'media',label:'تصویر شاخص',group:'media'}} value={post.cover_url} onChange={v=>setPost({...post,cover_url:String(v??'')})} pickers={pickers} flash={flash}/><Field label="خلاصه"><Textarea value={post.excerpt} onChange={excerpt=>setPost({...post,excerpt})}/></Field><Field label="متن مطلب"><Textarea rows={14} value={post.body} onChange={body=>setPost({...post,body})}/></Field>
        {post.post_type==='video'&&<div className="grid gap-3 sm:grid-cols-2"><Field label="منبع ویدیو"><Select options={['یوتیوب','ویدیو مستقیم','منبع بیرونی']} value={post.source_type==='youtube'?'یوتیوب':post.source_type==='direct'?'ویدیو مستقیم':'منبع بیرونی'} onChange={label=>setPost({...post,source_type:label==='یوتیوب'?'youtube':label==='ویدیو مستقیم'?'direct':'external'})}/></Field><Field label="نشانی HTTPS ویدیو"><Input value={post.source_url} onChange={source_url=>setPost({...post,source_url})}/></Field><Field label="مدت (ثانیه)"><Input value={String(post.duration_seconds??'')} onChange={v=>setPost({...post,duration_seconds:v?Number(v):null})}/></Field></div>}
        <p className="text-xs text-[var(--kv-muted)]">تنظیمات سئو در مرکز سئو مدیریت می‌شود.</p>{saveError&&<div role="alert" className="space-y-2"><p className="text-sm text-[var(--kv-danger)]">{saveError}</p><Btn size="sm" disabled={busy} onClick={()=>void save(post,'draft')}>تلاش دوباره برای ذخیره</Btn>{post.id&&<Btn size="sm" variant="soft" disabled={busy} onClick={()=>{void apiClient.get<{items:Post[]}>('/admin/editorial?limit=250').then(r=>{setPosts(r.items);const latest=r.items.find(p=>p.id===post.id);if(latest)edit(latest);}).catch(e=>setSaveError(cmsError(e)));}}>بارگذاری نسخهٔ سرور</Btn>}</div>}
        <div className="flex flex-wrap gap-2"><Btn variant="soft" disabled={busy||!post.title||!post.slug} onClick={()=>void save(post,'draft')}>{busy?'در حال ذخیره…':'ذخیره پیش‌نویس'}</Btn><Btn variant="accent" disabled={busy||!post.title||!post.slug||!!saveError} onClick={()=>setConfirm(true)}>انتشار</Btn>{post.id&&<Btn variant="ghost" disabled={busy} onClick={()=>void save(post,post.status==='archived'?'draft':'archived')}>{post.status==='archived'?'بازگردانی به پیش‌نویس':'بایگانی'}</Btn>}</div>
        {confirm&&<div className="space-y-3 rounded-lg border border-[var(--kv-line)] p-4"><p className="text-sm">محتوای فعلی این مطلب در سایت عمومی نمایش داده شود؟</p><Btn variant="accent" disabled={busy} onClick={()=>void save(post,'published')}>تأیید انتشار</Btn><Btn variant="ghost" disabled={busy} onClick={()=>setConfirm(false)}>انصراف</Btn></div>}
      </div>}
    </WorkspaceModal>
  </div>;
}
