import { useEffect, useMemo, useRef, useState } from 'react';
import { studioApi, type RegistryComponent, type SitePage } from '../data/experience-api';
import { Btn, Empty, ErrorState, Field, Input, LoadingState, Segmented, Select, WorkspaceModal } from '../components/primitives';
import { PreviewFrame } from '../components/cms-preview-frame';
import { PersianDatePicker } from '../components/persian-date-picker';
import { formatPersianDateTime } from '../data/persian-date';
import { clientValidate, FieldInput, fieldsOf, loadPickers, type PickerData } from './admin-section-editor';
import { cmsError, cmsWorkspaceApi, PAGE_STATUS, type DraftPage, type DraftSection, type Readiness } from './cms-api';
import { cn } from '../utils/cn';

const HERO_CHOICES = [
  { code: 'split', title: 'دو ستونه', detail: 'متن و تصویر کنار هم' },
  { code: 'mosaic', title: 'بنتو', detail: 'چند قاب تصویری' },
  { code: 'video', title: 'ویدیویی', detail: 'ویدیو تمام‌عرض با پوستر' },
  { code: 'fullviewport', title: 'تمام‌صفحه', detail: 'تصویر یا ویدیو در ارتفاع صفحه' },
  { code: 'editorial', title: 'ادیتوریال', detail: 'تیتر درشت و تصویر شاخص' },
] as const;
const STYLE_LABEL:Record<string,string>={background:'پس‌زمینه',foreground:'رنگ متن',border:'حاشیه',radius:'گردی گوشه',shadow:'سایه',padding:'فاصله داخلی',gap:'فاصله اجزا',width:'عرض',minHeight:'حداقل ارتفاع',typeScale:'اندازه متن',fontFamily:'فونت',align:'تراز',animation:'حرکت',mediaFit:'برش رسانه'};
const TOKEN_LABEL:Record<string,string>={inherit:'تم سایت',background:'پس‌زمینه',surface:'سطح',surfaceSecondary:'سطح دوم',primary:'اصلی',accent:'تأکیدی',textPrimary:'متن اصلی',textSecondary:'متن فرعی',onPrimary:'روی رنگ اصلی',none:'هیچ',line:'خط نازک',strong:'پررنگ',sm:'کوچک',md:'متوسط',lg:'بزرگ',xl:'خیلی بزرگ',narrow:'باریک',content:'محتوا',wide:'عریض',full:'تمام عرض',auto:'خودکار',screen:'تمام صفحه',body:'متن',display:'نمایشی',start:'راست',center:'وسط',end:'چپ',fade:'محو',rise:'بالا آمدن',zoom:'بزرگ‌نمایی',cover:'پر کردن',contain:'نمایش کامل'};
const widgetGroup=(c:RegistryComponent)=>c.kind==='global'?'سراسری':c.component_type==='data'?'فروش و داده':'محتوا و چیدمان';

export function PageWorkspace({pageId,flash,onClose,initialPanel='sections'}:{pageId:string;flash:(m:string)=>void;onClose:()=>void;initialPanel?:'sections'|'preview'}) {
  const [draft,setDraft]=useState<DraftPage|null>(null),[registry,setRegistry]=useState<RegistryComponent[]>([]),[pickers,setPickers]=useState<PickerData|null>(null);
  const [error,setError]=useState(''),[saveError,setSaveError]=useState(''),[saving,setSaving]=useState(false),[change,setChange]=useState(0),[saved,setSaved]=useState(0);
  const [selected,setSelected]=useState(''),[panel,setPanel]=useState<'sections'|'preview'|'properties'>(initialPanel),[device,setDevice]=useState<'desktop'|'tablet'|'mobile'>('desktop');
  const [leftTab,setLeftTab]=useState<'widgets'|'layers'>('widgets'),[inspectorTab,setInspectorTab]=useState<'content'|'style'|'advanced'>('content'),[widgetSearch,setWidgetSearch]=useState('');
  const [focusCanvas,setFocusCanvas]=useState(false),[draggingWidget,setDraggingWidget]=useState(false);
  const [styleSpec,setStyleSpec]=useState<Record<string,{values:string[];simple:boolean}>>({}),[previewMode,setPreviewMode]=useState<'draft'|'version'>('draft');
  const [preview,setPreview]=useState<SitePage|null>(null),[health,setHealth]=useState<Readiness|null>(null),[publishOpen,setPublishOpen]=useState(false),[busy,setBusy]=useState(false);
  const [versions,setVersions]=useState<Awaited<ReturnType<typeof studioApi.versions>>['items']|null>(null),[start,setStart]=useState<string|null>(null),[end,setEnd]=useState<string|null>(null),[summary,setSummary]=useState('');
  const current=useRef<DraftPage|null>(null),generation=useRef(0),persisted=useRef(0),inflight=useRef<Promise<boolean>|null>(null),mounted=useRef(true);
  const load=async()=>{setError('');try{const [d,r,p]=await Promise.all([cmsWorkspaceApi.draft(pageId),studioApi.registry(),loadPickers()]);current.current=d;setDraft(d);setRegistry(r.items);setStyleSpec(r.styleSpec);setPickers(p);generation.current=0;persisted.current=0;setChange(0);setSaved(0);setSaveError('');setSelected(d.sections[0]?.id??'');setPreviewMode('draft');setPreview(await studioApi.preview(pageId));}catch(e){setError(cmsError(e));}};
  useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;};},[pageId]);
  const edit=(next:DraftPage)=>{current.current=next;setDraft(next);setPreviewMode('draft');generation.current++;setChange(generation.current);setSaveError('');setHealth(null);};
  const save=async():Promise<boolean>=>{
    if(inflight.current)return inflight.current;
    if(!current.current||generation.current===persisted.current)return true;
    const invalid=current.current.sections.find(s=>Object.keys(clientValidate(fieldsOf(registry.find(c=>c.code===s.component_code)),s.payload)).length);
    if(invalid){setSelected(invalid.id);setInspectorTab('content');setSaveError('فیلدهای الزامی ویجت را تکمیل کنید، سپس پیش‌نویس را ذخیره کنید.');return false;}
    const d=current.current,g= generation.current;
    setSaving(true);setSaveError('');
    const promise=(async()=>{try{
      const result=await cmsWorkspaceApi.save(d);
      if(!mounted.current)return false;
      persisted.current=g;setSaved(g);
      const next=generation.current===g?{...result,permissions:current.current?.permissions}:{...current.current!,draft_revision:result.draft_revision};current.current=next;setDraft(next);
      try{setPreviewMode('draft');setPreview(await studioApi.preview(pageId));}catch(e){setError(`پیش‌نمایش: ${cmsError(e)}`);}
      return true;
    }catch(e){if(mounted.current)setSaveError(cmsError(e));return false;}finally{inflight.current=null;if(mounted.current)setSaving(false);}})();inflight.current=promise;return promise;
  };
  useEffect(()=>{if(change===saved||saving||saveError||current.current?.sections.some(s=>Object.keys(clientValidate(fieldsOf(registry.find(c=>c.code===s.component_code)),s.payload)).length))return;const t=window.setTimeout(()=>void save(),750);return()=>window.clearTimeout(t);},[change,saved,saving,saveError,registry]);
  useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(generation.current!==persisted.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[]);
  const close=()=>{if(generation.current!==persisted.current||inflight.current){setSaveError('تغییرات هنوز ذخیره نشده‌اند؛ ذخیره را دوباره انجام دهید یا نسخهٔ سرور را بارگذاری کنید.');return;}onClose();};
  const run=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn();}catch(e){setSaveError(cmsError(e));}finally{setBusy(false);}};
  const updateSection=(id:string,next:Partial<DraftSection>)=>{if(current.current?.permissions?.includes('cms:edit'))edit({...current.current,sections:current.current.sections.map(s=>s.id===id?{...s,...next}:s)});};
  const move=(id:string,delta:number)=>{if(!current.current?.permissions?.includes('cms:edit'))return;const list=[...current.current.sections];const i=list.findIndex(s=>s.id===id),j=i+delta;if(i<0||j<0||j>=list.length)return;const [item]=list.splice(i,1);list.splice(j,0,item!);edit({...current.current,sections:list.map((s,position)=>({...s,position:position+1}))});};
  const insert=(code:string,at?:number)=>{const d=current.current,c=registry.find(item=>item.code===code);if(!d?.permissions?.includes('cms:edit')||!c)return;const payload:Record<string,unknown>={};for(const f of fieldsOf(c))if(f.default!==undefined&&f.default!=='')payload[f.key]=f.default;if(fieldsOf(c).some(f=>f.key==='title'))payload.title=c.title.replace(/\s*\([^)]*\)/g,'');const id=crypto.randomUUID(),list=[...d.sections];list.splice(at??list.length,0,{id,component_code:c.code,title:c.title.replace(/\s*\([^)]*\)/g,''),payload,visible:true,position:0,variant:c.variants?.[0]??'default',section_theme:'inherit',style_overrides:{},responsive_config:{}});edit({...d,sections:list.map((s,position)=>({...s,position:position+1}))});setSelected(id);setInspectorTab('content');setFocusCanvas(false);setPanel('properties');};
  const duplicate=(id:string)=>{const d=current.current;if(!d?.permissions?.includes('cms:edit'))return;const i=d.sections.findIndex(s=>s.id===id);if(i<0)return;const list=[...d.sections];const copy={...list[i]!,id:crypto.randomUUID(),title:`${list[i]!.title} (کپی)`,payload:{...list[i]!.payload},style_overrides:{...list[i]!.style_overrides},responsive_config:{...list[i]!.responsive_config}};list.splice(i+1,0,copy);edit({...d,sections:list.map((s,position)=>({...s,position:position+1}))});setSelected(copy.id);setPanel('properties');};
  const canEdit=draft?.permissions?.includes('cms:edit')===true,canPublish=draft?.permissions?.includes('cms:publish')===true;
  const section=draft?.sections.find(s=>s.id===selected),component=registry.find(c=>c.code===section?.component_code);
  const fields=fieldsOf(component),validation=section?clientValidate(fields,section.payload):{};
  const invalidCount=draft?.sections.filter(s=>Object.keys(clientValidate(fieldsOf(registry.find(c=>c.code===s.component_code)),s.payload)).length).length??0;
  const visualPreview=useMemo(()=>{if(!preview||!draft||previewMode==='version')return preview;const byId=new Map(preview.sections.map(s=>[s.id,s]));return {...preview,title:draft.title,path:draft.path,sections:draft.sections.filter(s=>s.visible).map(s=>({...byId.get(s.id),...s,component_type:byId.get(s.id)?.component_type??registry.find(c=>c.code===s.component_code)?.component_type??'section',resolved:byId.get(s.id)?.resolved})).sort((a,b)=>a.position-b.position)} as SitePage;},[preview,draft,registry,previewMode]);
  const widgets=registry.filter(c=>c.active!==false&&`${c.title} ${c.code}`.toLowerCase().includes(widgetSearch.trim().toLowerCase()));
  const openPublish=()=>void run(async()=>{if(!await save()||generation.current!==persisted.current)return;const h=await cmsWorkspaceApi.readiness(pageId);setHealth(h);setPublishOpen(true);});
  return <WorkspaceModal open onClose={close} title={draft?`ویرایش «${draft.title}»`:'ویرایش صفحه'} subtitle="پیش‌نویس در سرور ذخیره می‌شود؛ سایت عمومی فقط نسخهٔ منتشرشده را نمایش می‌دهد.">
    {!draft?(error?<ErrorState message={error} onRetry={()=>void load()}/>:<LoadingState/>):<div className="min-w-0 space-y-4">
      <div className="flex flex-wrap items-center gap-2"><span className="text-xs">{PAGE_STATUS[draft.status]} · <span role="status">{saving?'در حال ذخیره…':saveError?'ذخیره انجام نشد':invalidCount?'فیلدهای الزامی را کامل کنید':change!==saved?'تغییرات ذخیره‌نشده':'ذخیره شد'}</span></span><Btn size="sm" variant="soft" disabled={!canEdit||saving||busy} onClick={()=>void save()}>ذخیره پیش‌نویس</Btn><Btn size="sm" variant="soft" disabled={saving||busy} onClick={()=>void run(async()=>{if(await save()&&generation.current===persisted.current){setPreview(await studioApi.preview(pageId));setPreviewMode('draft');setPanel('preview');}})}>پیش‌نمایش</Btn><Btn size="sm" variant="soft" disabled={busy||saving||change!==saved} onClick={()=>void run(async()=>setVersions((await studioApi.versions(pageId)).items))}>تاریخچه</Btn><Btn size="sm" variant="accent" disabled={!canPublish||busy||saving||!!saveError||change!==saved||!!invalidCount} onClick={openPublish}>بررسی و انتشار</Btn></div>
      {!!pickers?.errors.length&&<ErrorState message="برخی فهرست‌های انتخاب بارگذاری نشدند" onRetry={()=>void loadPickers().then(setPickers)}/>}
      {saveError&&<div role="alert" className="space-y-2 rounded-lg border border-[var(--kv-danger)] p-3 text-sm"><p>{saveError}</p><div className="flex flex-wrap gap-2"><Btn size="sm" disabled={saving} onClick={()=>void save()}>تلاش دوباره</Btn><Btn size="sm" disabled={saving} variant="soft" onClick={()=>void load()}>بارگذاری نسخهٔ سرور و کنارگذاشتن تغییرات ذخیره‌نشده</Btn></div></div>}
      {!canEdit&&<p className="text-sm">دسترسی شما فقط برای مشاهدهٔ پیش‌نویس است.</p>}
      <div className="xl:hidden"><Segmented options={[{v:'sections' as const,label:'ویجت‌ها و لایه‌ها'},{v:'preview' as const,label:'بوم صفحه'},{v:'properties' as const,label:'تنظیمات'}]} value={panel} onChange={setPanel}/></div>
      <div className={cn('grid min-w-0 gap-3 xl:h-[calc(90vh-190px)] xl:min-h-0',focusCanvas?'grid-cols-1':'xl:grid-cols-[240px_minmax(0,1fr)_300px]')}>
        <aside className={cn('min-w-0 rounded-xl border border-[var(--kv-line)] bg-[var(--kv-surface)] p-3 xl:overflow-y-auto',(focusCanvas||panel!=='sections')&&'hidden xl:block',focusCanvas&&'xl:!hidden')} aria-label="کتابخانه ویجت و لایه‌ها">
          <Segmented options={[{v:'widgets' as const,label:'ویجت‌ها'},{v:'layers' as const,label:'لایه‌ها'}]} value={leftTab} onChange={setLeftTab}/>
          {leftTab==='widgets'?<div className="mt-4 space-y-4">
            <Input ariaLabel="جستجوی ویجت" placeholder="جستجوی ویجت…" value={widgetSearch} onChange={setWidgetSearch}/>
            <p className="text-xs text-[var(--kv-muted)]">ویجت را انتخاب کنید یا به بوم بکشید.</p>
            {['محتوا و چیدمان','فروش و داده','سراسری'].map(group=>{const items=widgets.filter(c=>widgetGroup(c)===group);return items.length?<section key={group} className="space-y-2"><h3 className="text-xs font-bold text-[var(--kv-muted)]">{group}</h3><div className="grid grid-cols-2 gap-2">{items.map(c=><button key={c.code} type="button" draggable={canEdit} onDragStart={e=>{e.dataTransfer.setData('application/x-kv-widget',c.code);setDraggingWidget(true);}} onDragEnd={()=>setDraggingWidget(false)} disabled={!canEdit} onClick={()=>insert(c.code)} className="min-h-20 rounded-lg border border-[var(--kv-line)] p-2 text-right text-xs transition-colors hover:border-[var(--kv-accent)] hover:bg-[var(--kv-surface-2)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--kv-accent)] disabled:opacity-50"><span className="mb-2 block text-xl text-[var(--kv-accent)]" aria-hidden="true">▦</span><span className="font-bold leading-5">{c.title.replace(/\s*\([^)]*\)/g,'')}</span></button>)}</div></section>:null;})}
            {!widgets.length&&<Empty title="ویجتی پیدا نشد" desc="عبارت دیگری جستجو کنید."/>}
          </div>:<div className="mt-4 space-y-3">
            <Field label="عنوان صفحه"><Input value={draft.title} onChange={title=>{if(canEdit)edit({...draft,title});}}/></Field>
            <Field label="مسیر صفحه"><Input value={draft.path} onChange={path=>{if(canEdit)edit({...draft,path});}}/></Field>
            <p className="text-xs text-[var(--kv-muted)]">بخش‌ها را بکشید یا با دکمه‌ها جابه‌جا کنید.</p>
            {draft.sections.map((s,i)=><div key={s.id} draggable={canEdit} onDragStart={e=>e.dataTransfer.setData('application/x-kv-layer',s.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const code=e.dataTransfer.getData('application/x-kv-widget');if(code){insert(code,i);return;}const from=draft.sections.findIndex(x=>x.id===e.dataTransfer.getData('application/x-kv-layer'));if(from>=0)move(draft.sections[from]!.id,i-from);}} className={cn('rounded-lg border p-2',selected===s.id?'border-[var(--kv-accent)] bg-[var(--kv-surface-2)]':'border-[var(--kv-line)]')}>
              <button type="button" className="w-full break-words text-right text-sm font-bold" onClick={()=>{setSelected(s.id);setPanel('properties');}}>{i+1}. {s.title||registry.find(c=>c.code===s.component_code)?.title||'بخش'} {!s.visible&&<span className="text-xs font-normal text-[var(--kv-muted)]">(پنهان)</span>}</button>
              <div className="mt-2 flex flex-wrap gap-1"><Btn size="sm" variant="ghost" disabled={!canEdit||i===0} onClick={()=>move(s.id,-1)}>↑</Btn><Btn size="sm" variant="ghost" disabled={!canEdit||i===draft.sections.length-1} onClick={()=>move(s.id,1)}>↓</Btn><Btn size="sm" variant="ghost" disabled={!canEdit} onClick={()=>updateSection(s.id,{visible:!s.visible})}>{s.visible?'پنهان':'نمایش'}</Btn><Btn size="sm" variant="ghost" disabled={!canEdit} onClick={()=>duplicate(s.id)}>تکثیر</Btn><Btn size="sm" variant="ghost" disabled={!canEdit} onClick={()=>{edit({...draft,sections:draft.sections.filter(x=>x.id!==s.id).map((x,position)=>({...x,position:position+1}))});if(selected===s.id)setSelected('');}}>حذف</Btn></div>
            </div>)}
            {!draft.sections.length&&<Empty title="صفحه خالی است" desc="از زبانه ویجت‌ها یک بخش اضافه کنید."/>}
          </div>}
        </aside>
        <section className={cn('min-w-0 rounded-xl border border-[var(--kv-line)] bg-[var(--kv-surface-2)] p-3 xl:overflow-y-auto',panel!=='preview'&&'hidden xl:block',focusCanvas&&'block')} aria-label="بوم صفحه" onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-kv-widget'))e.preventDefault();}} onDrop={e=>{const code=e.dataTransfer.getData('application/x-kv-widget');if(code){e.preventDefault();setDraggingWidget(false);insert(code);}}}>
          <div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-bold">بوم صفحه</h3><p className="text-xs text-[var(--kv-muted)]">برای ویرایش روی هر بخش کلیک کنید.</p></div><div className="flex flex-wrap items-center gap-2"><Btn size="sm" variant="soft" onClick={()=>setFocusCanvas(v=>!v)}>{focusCanvas?'نمایش پنل‌ها':'بوم تمام‌عرض'}</Btn><Segmented options={[{v:'desktop' as const,label:'دسکتاپ'},{v:'tablet' as const,label:'تبلت'},{v:'mobile' as const,label:'موبایل'}]} value={device} onChange={setDevice}/></div></div>
          {previewMode==='version'&&<div className="mb-3 flex items-center justify-between gap-2 rounded-lg border border-[var(--kv-line)] p-2 text-xs"><span>در حال مشاهده نسخه تاریخی</span><Btn size="sm" variant="soft" onClick={()=>void run(async()=>{setPreview(await studioApi.preview(pageId));setPreviewMode('draft');})}>بازگشت به پیش‌نویس</Btn></div>}
          {error&&<ErrorState message={error} onRetry={()=>void run(async()=>{setPreview(await studioApi.preview(pageId));setError('');})}/>}
          {visualPreview&&<div className="relative"><PreviewFrame page={visualPreview} device={device} selectedId={selected} onSelect={id=>{setSelected(id);setInspectorTab('content');setFocusCanvas(false);setPanel('properties');}}/>{draggingWidget&&<div className="absolute inset-0 z-10 flex items-center justify-center rounded-xl border-2 border-dashed border-[var(--kv-accent)] bg-[var(--kv-surface)]/75 text-sm font-bold text-[var(--kv-accent)]" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();e.stopPropagation();const code=e.dataTransfer.getData('application/x-kv-widget');setDraggingWidget(false);if(code)insert(code);}}>رها کنید تا ویجت به صفحه افزوده شود</div>}</div>}
          {!visualPreview&&!error&&<Empty title="پیش‌نمایش در حال آماده‌سازی است" desc="پس از بارگذاری صفحه، بوم نمایش داده می‌شود."/>}
          <div className="mt-3 rounded-lg border border-dashed border-[var(--kv-line)] p-3 text-center text-xs text-[var(--kv-muted)]">ویجت‌ها را اینجا رها کنید تا به انتهای صفحه اضافه شوند.</div>
        </section>
        <section className={cn('min-w-0 rounded-xl border border-[var(--kv-line)] bg-[var(--kv-surface)] p-3 xl:overflow-y-auto',(focusCanvas||panel!=='properties')&&'hidden xl:block',focusCanvas&&'xl:!hidden')} aria-label="تنظیمات بخش">
          {!section?<Empty title="بخشی انتخاب کنید" desc="روی یک بخش در بوم یا لایه‌ها کلیک کنید."/>:<div className="space-y-4">
            <div><h3 className="text-sm font-bold">{section.title}</h3><p className="text-xs text-[var(--kv-muted)]">{component?.title??section.component_code}</p></div>
            <Segmented options={[{v:'content' as const,label:'محتوا'},{v:'style' as const,label:'ظاهر'},{v:'advanced' as const,label:'پیشرفته'}]} value={inspectorTab} onChange={setInspectorTab}/>
            {inspectorTab==='content'&&<div className="space-y-4">
              <Field label="عنوان داخلی"><Input value={section.title} onChange={title=>updateSection(section.id,{title})}/></Field>
              {['hero','image_hero','video_hero'].includes(section.component_code)&&<fieldset className="space-y-2"><legend className="text-sm font-bold">قالب هیرو</legend><div className="grid grid-cols-2 gap-2">{HERO_CHOICES.map(choice=><button key={choice.code} type="button" aria-pressed={(section.payload.template??'split')===choice.code} disabled={!canEdit} onClick={()=>updateSection(section.id,{payload:{...section.payload,template:choice.code}})} className={cn('min-h-16 rounded-lg border p-2 text-right text-xs hover:border-[var(--kv-accent)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--kv-accent)]',section.payload.template===choice.code?'border-[var(--kv-accent)] bg-[var(--kv-surface-2)]':'border-[var(--kv-line)]')}><b className="block">{choice.title}</b><span className="mt-1 block text-[var(--kv-muted)]">{choice.detail}</span></button>)}</div></fieldset>}
              {fields.filter(f=>!f.showIf||Object.entries(f.showIf).every(([k,v])=>String(section.payload[k]??fields.find(x=>x.key===k)?.default??'')===v)).map(f=><div key={f.key}><FieldInput field={f} value={section.payload[f.key]} onChange={v=>{const p={...section.payload};if(v===undefined||v==='')delete p[f.key];else p[f.key]=v;updateSection(section.id,{payload:p});}} pickers={pickers} flash={flash}/>{validation[f.key]&&<p role="alert" className="text-xs text-[var(--kv-danger)]">{validation[f.key]}</p>}</div>)}
              {(component?.presetDefinitions?.length??0)>0&&<Field label="چیدمان آماده"><Select options={['انتخاب کنید',...component!.presetDefinitions.map((_,i)=>`چیدمان ${i+1}`)]} value="انتخاب کنید" onChange={label=>{const i=Number(label.replace('چیدمان ',''))-1,p=component!.presetDefinitions[i];if(p)updateSection(section.id,{variant:p.variant,payload:{...section.payload,...p.payload},style_overrides:p.style_overrides,responsive_config:p.responsive_config});}}/></Field>}
              {component?.variants?.length&&<Field label="سبک نمایش"><Select options={component.variants} labels={Object.fromEntries(component.variants.map((v,i)=>[v,`سبک ${i+1} · ${v}`]))} value={section.variant} onChange={variant=>updateSection(section.id,{variant})}/></Field>}
            </div>}
            {inspectorTab==='style'&&<div className="space-y-3"><p className="text-xs text-[var(--kv-muted)]">رنگ‌ها و اندازه‌ها از توکن‌های تم سایت انتخاب می‌شوند.</p>{Object.entries(styleSpec).map(([key,spec])=><Field key={key} label={STYLE_LABEL[key]??key}><Select options={['',...spec.values]} labels={{'':'پیش‌فرض',...Object.fromEntries(spec.values.map(v=>[v,TOKEN_LABEL[v]??v]))}} value={String(section.style_overrides[key]??'')} onChange={value=>{const next={...section.style_overrides};if(value)next[key]=value;else delete next[key];updateSection(section.id,{style_overrides:next});}}/></Field>)}<Field label="تیرگی لایه (۰ تا ۹۰)"><Input type="number" value={String(section.style_overrides.overlay??0)} onChange={value=>updateSection(section.id,{style_overrides:{...section.style_overrides,overlay:Math.max(0,Math.min(90,Number(value)||0))}})}/></Field></div>}
            {inspectorTab==='advanced'&&<div className="space-y-4">
              <Field label="نمایش بخش"><Select options={['inherit','light','dark','campaign']} labels={{inherit:'تم سایت',light:'روشن',dark:'تیره',campaign:'کمپین'}} value={section.section_theme} onChange={section_theme=>updateSection(section.id,{section_theme})}/></Field>
              <h4 className="text-sm font-bold">نمایش واکنش‌گرا</h4>
              {([['hideOnMobile','مخفی در موبایل'],['hideOnTablet','مخفی در تبلت'],['hideOnDesktop','مخفی در دسکتاپ']] as const).map(([key,label])=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={section.responsive_config[key]===true} disabled={!canEdit} onChange={e=>updateSection(section.id,{responsive_config:{...section.responsive_config,[key]:e.target.checked}})}/>{label}</label>)}
              <Field label="تعداد ستون در موبایل"><Select options={['','1','2','3']} labels={{'':'پیش‌فرض'}} value={String(section.responsive_config.mobileColumns??'')} onChange={v=>{const next={...section.responsive_config};if(v)next.mobileColumns=Number(v);else delete next.mobileColumns;updateSection(section.id,{responsive_config:next});}}/></Field>
              <Field label="تعداد ستون در تبلت"><Select options={['','1','2','3','4']} labels={{'':'پیش‌فرض'}} value={String(section.responsive_config.tabletColumns??'')} onChange={v=>{const next={...section.responsive_config};if(v)next.tabletColumns=Number(v);else delete next.tabletColumns;updateSection(section.id,{responsive_config:next});}}/></Field>
              <Btn size="sm" variant="soft" disabled={!canEdit} onClick={()=>duplicate(section.id)}>تکثیر این بخش</Btn>
            </div>}
          </div>}
        </section>
      </div>
    </div>}
    <WorkspaceModal open={publishOpen} onClose={()=>{if(!busy)setPublishOpen(false);}} title="بررسی پیش از انتشار"><div className="mx-auto max-w-2xl space-y-4">
      <h3 className="font-bold">{health?.errors.length?'دارای خطا':health?.warnings.length?'نیازمند بررسی':'آماده انتشار'}</h3>{health?.errors.map((e,i)=><p key={i} role="alert" className="text-sm text-[var(--kv-danger)]">{e}</p>)}{health?.warnings.map((e,i)=><p key={i} className="text-sm">{e}</p>)}<h4 className="font-bold">تفاوت با نسخهٔ منتشرشده</h4><ul className="list-inside list-disc space-y-2 text-sm">{health?.diff.map((d,i)=><li key={i}>{d}</li>)}</ul>{health?.diff.length===0&&<p className="text-sm">محتوا تغییری نکرده است.</p>}<PersianDatePicker label="شروع انتشار (اختیاری)" withTime value={start} onChange={setStart}/><PersianDatePicker label="پایان انتشار (اختیاری)" withTime value={end} onChange={setEnd}/><Field label="خلاصه تغییرات"><Input value={summary} onChange={setSummary}/></Field>{saveError&&<p role="alert" className="text-sm text-[var(--kv-danger)]">{saveError}</p>}<Btn variant="accent" disabled={!canPublish||busy||!health?.ready||!!saveError||change!==saved} onClick={()=>void run(async()=>{const r=await studioApi.publish(pageId,{scheduledStartAt:start,scheduledEndAt:end,changeSummary:summary,expectedRevision:health!.revision});flash(r.status==='scheduled'?'انتشار زمان‌بندی شد':'صفحه منتشر شد');setPublishOpen(false);await load();})}>{busy?'در حال انتشار…':start?'تأیید زمان‌بندی':'تأیید انتشار فوری'}</Btn>
    </div></WorkspaceModal>
    <WorkspaceModal open={versions!==null} onClose={()=>{if(!busy)setVersions(null);}} title="تاریخچه نسخه‌ها"><div className="space-y-3">{!versions?.length&&<Empty title="هنوز نسخه‌ای منتشر نشده" desc="هر انتشار یک نسخهٔ مستقل ثبت می‌کند."/>}{versions?.map(v=><article key={v.id} className="space-y-2 border-b border-[var(--kv-line)] py-3"><b>نسخه {v.version.toLocaleString('fa-IR')}</b><p className="text-xs">{formatPersianDateTime(v.created_at)} · {v.changed_by_name??'—'} · {v.change_summary??'بدون خلاصه'}</p><div className="flex gap-2"><Btn size="sm" disabled={busy} onClick={()=>void run(async()=>{setPreview(await cmsWorkspaceApi.versionPreview(pageId,v.version));setPreviewMode('version');setPanel('preview');setVersions(null);})}>پیش‌نمایش نسخه</Btn><Btn size="sm" variant="soft" disabled={!canEdit||busy} onClick={()=>void run(async()=>{await studioApi.restore(pageId,v.version);flash('نسخه به پیش‌نویس بازگردانده شد؛ انتشار جداگانه لازم است');setVersions(null);await load();})}>بازگردانی به پیش‌نویس</Btn></div></article>)}</div></WorkspaceModal>
  </WorkspaceModal>;
}
